### ISSUE TITLE
[critical] Some commands are not executed - but tests are however all green 

### ISSUE THREAD

**Issue by xOctave** [AxonFramework/AxonBank#19]
The     
`@CommandHandler
public void handle(DebitSourceBankAccountCommand command)`
and 
`@CommandHandler
public void handle(CreditDestinationBankAccountCommand command) `
are never invoked. 

I'm not sure why because they seems to be pushed on the bus

`        DebitSourceBankAccountCommand command = new DebitSourceBankAccountCommand(...);
        commandBus.dispatch(asCommandMessage(command), LoggingCallback.INSTANCE);`

This is confirmed by two facts 
- Incomplete code coverage > BankAccountCommandHandler | 100% (1/1) | 20% (1/5) | 22% (4/18) -- | -- | -- | --
- If we remove these methods, the tests are still passing, which is quite surprising.

Could you have a look at that?
Thanks a lot.
Octave

**Comment by smcvb** [comment]
Thanks for drafting this issue, @hsq125, but I need to apologize as well right away.
We're not pursuing active development on this sample project anymore.
In fact, I'm on the verge of archiving it.

The fact we've made this decision is because we've got other sample projects better suited to show what Axon can bring you.
These are the [GiftCard](https://github.com/AxonIQ/giftcard-demo) or the [Hotel](https://github.com/AxonIQ/hotel-demo) applications.
