### ISSUE TITLE
how transaction works

### ISSUE THREAD

**Issue by stun4j** [AxonFramework/AxonBank#2]
I'm wondering how saga transaction works,does it support distributed-transacton or only local transaction?
I wrote a mock code to verify simple transaction( org.axonframework.samples.bank.command.BankAccount#on(MoneyAddedEvent event) ),see below:
<code>
    @EventHandler
    public void on(MoneyAddedEvent event) {
        //mock raise exception here->
        if (event.getAmount() == 5) throw new RuntimeException("mock ex trigger rollback");
        //<-
        balanceInCents += event.getAmount();
    }
<code>

the detail scenario is 'bank transfer': add 10 to account A,also add 10 to account B,then transfer 5 from A to B,which will raise excetion,under my understanding,nothing would be changed,but the result shows that A lost 5,B still 10,btw,I make a little change to use JPA(with MySQL5Dialect)&transaction

appreciate your feedback,thanks a lot....

**Comment by fvyaba** [comment]
anyone can help?

**Comment by smcvb** [comment]
If I understand your question correctly @fvyaba , I have to say the process is a little different than normal distributed/local transactions.

The Axon Saga is a form of Transaction Manager on, but than for [BASE](https://en.wikipedia.org/wiki/Eventual_consistency) (eventually consistent) transactions rather than ACID (what I think you're referring to).

Another nice reference to explain the process is the '[Starbucks Does Not Use Two-Phase Commit](http://www.enterpriseintegrationpatterns.com/ramblings/18_starbucks.html)' blog post by Gregor Hohpe.

**Comment by stun4j** [comment]
thanks for your response @smcvb,yes,I understand SAGA(BASE),but still,in my scenario, I can't understand why money transfer fails but the compensating action(instead of ACID) not triggered,which means account A lost 5 meanwhile account B got nothing as well...

the only change I made as below:
1.'mock raising an exception' before account B add money
2.enable JpaSagaStore instead of InMemoryEventStorageEngine(because in-memory solution not works,but still JpaSagaStore not works as well)

anything I do wrong? or miss understanding about AXON SAGA programming-model?

**Comment by smcvb** [comment]
Aah sorry, now I follow. You thought that when an exception is thrown in the saga, that the complete handling of the event within the aggregate would also be roll backed, right?
That's not the case tough, so the behavior as you see it is as expected.

You could view the Saga as the query side of the app, hence stating that it's just listening to the events and 
processing it in a way it sees fit (so depending on how you've implemented it). As such it by default has not control over the aggregates state by rolling back the event from actually happening.

**Comment by stun4j** [comment]
thank you very much@smcvb,so,first of all,AXON-SAGA is an event-tracking mechanism crossing aggregates,right?

I'm very interested in your demo which shows an very classical scenario about crossing-boundary transaction ,but I did't found any compensating-staff within your demo,so,what's your suggestion about taking the compensating action or does AXON(SAGA) has the ability doing so via some magic API(sth like lifecycle-replay)?

actually,the reason why I wrote the exception-mocking code is that I believe AXON would have a very good start to solve this kinda problem and I think your demo is a very good start demonstrating the first paragraph('Not every command is able......So we do expect some form of consistency,ultimately'),SAGAS section,AXON official documentation.

ok,the attachment is my upgraded BankAccount.java for more clearly showing my intention,and hoping your feedback, sincerely

[BankAccount.java.zip](https://github.com/AxonFramework/AxonBank/files/722536/BankAccount.java.zip)

**Comment by smcvb** [comment]
No prob @fvyaba! I'm happy to help :)

To answer your first question: yes, that's one way of putting it. The Saga's in Axon are used to achieve orchestration among several aggregates. As such, 1 or more aggregates could be bound to a Saga. So for example, a saga for a bank transfer can be tied to two bank account aggregates.

To answer your second question: I'd probably send a command when handling the exception rather than just throwing the exception. One of Allard's webinars where he explains a simple Axon implementation (also a bank example) has some example code of this (around 33min). 

The 'live coding session' webinars show several nice examples which might clear up more stuff :)

**Comment by stun4j** [comment]
many thanks @smcvb,I will keep an eye on this
